### ISSUE TITLE
Complex (?) case of variants

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#113]
I defined the following variants for an RF connector.
The connector can either be a wire, U.Fl connector or SMA Edge Board connector in 1 footprint and schematic symbol.
I didn't find the method yet (if any) to get the right description and reference to appear in the output.

![image](https://user-images.githubusercontent.com/1504752/33635462-5933c176-da18-11e7-9945-ed8b914286af.png)

**Comment by hildogjr** [comment]
Clarify me, please (thats is the output expected?).

**Comment by hildogjr** [comment]
Close by inactivity.
