### ISSUE TITLE
Farnell scrap module freeze process

### ISSUE THREAD

**Issue by hildogjr** [hildogjr/KiCost#114]
Every time that I scrap for prices using the farnell module the process still freeze in 0%, not going on or give me some error. I don't now if is a error in the scrap module or it just need to be updated to some web page change.
To work around this issue I am using `--include digikey mouser rs tme newark` or `--exclude farnell`.

**Comment by adamheinrich** [comment]
I have the same problem with Farnell right now.

**Comment by adamheinrich** [comment]
Quick observations:

Setting User-agent to a newer browser and adding the following headers helps:

```
req.add_header('Accept', 'text/html')
req.add_header('Cookie', 'foo=bar')
```

**Comment by adamheinrich** [comment]
However, I'm not able to find a good database of User-agent strings to update the current one. The one I successfully used to access Farnell using KiCost was `Chrome/62.0.3202.94`, while the newest one at http://www.useragentstring.com/pages/useragentstring.php?name=Chrome is `Chrome/41.0.2228.0`.

**Comment by adamheinrich** [comment]
This one looks good: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/

PR comes in a few minutes...
