### ISSUE TITLE
The script calculates the wrong price for eu.mouser.com/pl.mouser.com.

### ISSUE THREAD

**Issue by Cinek75** [hildogjr/KiCost#12]
I live in Europe and script for the  mouser store is redirected to the page eu.mouser.com or pl.mouser.com where prices are given in euros (€).
For example QTY=1:
Digikey, and Newark correctly indicate the price Pic12F508-I / SN = $0,56
For eu.mouser.com default currency is euro.
The script displays the price, multiplied by 100, ie. Price = $ 615.00.
Properly should be €0,0615 -> $0,688

**Comment by ghost** [comment]
In the UK we have http://www.mouser.co.uk and it doesn't auto redirect. More of a moan than an actual request though. :)

**Comment by romain145** [comment]
Linked to #56 and #65.

**Comment by hildogjr** [comment]
Inside the `mouse.py` you can force change the link. But this still being a work around.
