### ISSUE TITLE
Support for RScomponents

### ISSUE THREAD

**Issue by karrika** [hildogjr/KiCost#14]
I would like to add support for RScomponents.

**Comment by kasbah** [comment]
Just FYI, if you output in a format compatible with my extension: [monostable/1clickBOM](https://github.com/monostable/1clickBOM), you could support all the retailers it supports which includes RS.

**Comment by FlYnN91** [comment]
+1 for this

**Comment by glcerone** [comment]
From version 0.1.31 Kicost supports also Farnel and RS Components.

**Comment by hildogjr** [comment]
Closed!

**Comment by nickoe** [comment]
Why is this bug not marked as closed?

**Comment by hildogjr** [comment]
I don't know. But there are a lot of others in same status (already fixed / implemented but opened yet).
I think, really active (in discussion or implementation) we have 10 or less (and 40 opened / the author of the issue forgotten to close).

**Comment by hildogjr** [comment]
Can @xesscorp (owner of the directory) close issues or just the author?
