### ISSUE TITLE
KiCost asks for wxPython to be installed when it is already installed.

### ISSUE THREAD

**Issue by xesscorp** [hildogjr/KiCost#140]
This happens for both Python 2.7 and 3.6.

Terminal error report:

$ kicost
You don't have the wxPython dependence to run the GUI interface. Run once of the follow commands in terminal to install them:
pip install wxPython # For python 2.5
pip3 install wxPython # For python 3.0+
Or download from last version from <https://wxpython.org/>

pip report:

$ pip install wxPython
Requirement already satisfied: wxPython in c:\python27-32\lib\site-packages
Requirement already satisfied: six in c:\python27-32\lib\site-packages (from wxPython)

$ pip list | grep -i wxpython
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
wxPython (4.0.0b2)
wxPython-common (3.0.2.0)

**Comment by hildogjr** [comment]
It was a error in the `from eda_tools import eda_tools`, that now is `eda_tools_dict`. The error was arising.
I correct this and also improve how to deal with, raising the correct error.
