### ISSUE TITLE
# parallel processes should be initialized to a value greater than 1 in the GUI.

### ISSUE THREAD

**Issue by xesscorp** [hildogjr/KiCost#142]
The number of parallel porcesses is initialized to 1 in the last version of the kicost GUI that I was able to run. It should probably be set to a higher value.

**Comment by hildogjr** [comment]
DONE
This is just change of the initialization default value. But after the first use is saved the user configurations on the Windows Registry / Linux Configuration File `.KiCost` on $HOME.

**Comment by hildogjr** [comment]
I put it 6.
