### ISSUE TITLE
kicost GUI progress bar.

### ISSUE THREAD

**Issue by xesscorp** [hildogjr/KiCost#143]
The kicost GUI should show a progress bar as the program runs. (Not the progress bar shown in the terminal window.)

**Comment by hildogjr** [comment]
Maybe, call kicost as a thread and deal with the output to generate the process bar and the messages/warning dialog.

**Comment by hildogjr** [comment]
Re-opening because #144 was already fixed and this may need some work around in the `tqdm`.
https://github.com/tqdm/tqdm/issues/172
