### ISSUE TITLE
Errors that occur with the kicost GUI should appear in a dialog window.

### ISSUE THREAD

**Issue by xesscorp** [hildogjr/KiCost#144]
Errors/warnings/log messages should appear in a dialog window when the kicost GUI is used. (Not in the terminal window.)

**Comment by hildogjr** [comment]
Merging with #143, add also a process bar.
"Maybe, call kicost as a thread and deal with the output to generate the process bar and the messages/warning dialog."

**Comment by hildogjr** [comment]
For the process bar update process, wait for `tqdm 5`? https://github.com/tqdm/tqdm/issues/172 (intended to use the average time and other informations already computed).
Check for solutions and work around (https://github.com/tqdm/tqdm/issues/494).

**Comment by hildogjr** [comment]
Necessary (better way) redirect the sdtout to a class that overwrite the `sys.stdout` (https://stackoverflow.com/questions/21341096/redirect-print-to-string-list) and use this on the `multiprocess.call(kicost())`. But this is creating some issues when run as parallel scraping.

**Comment by hildogjr** [comment]
Change the print output to message box on the GUI, but missing fix related with #193 to work fine.

**Comment by hildogjr** [comment]
For reference
https://www.thecodingforums.com/threads/wxpython-redirect-the-stdout-to-a-textctrl.515815/
