### ISSUE TITLE
ability to use boolean operators on Variant

### ISSUE THREAD

**Issue by Shackmeister** [hildogjr/KiCost#148]
Hey People
as discussed some time ago on kicad forums [see here:](https://forum.kicad.info/t/latest-version-of-kicost-faster-custom-pricing/1953/72), I would like to request a boolean operator system for determining which variant should be used.

**Comment by hildogjr** [comment]
After some study mine, you still can using the regular expressions. For the variants:

    test
    testeee
    test0
    teste0

The `^((?!test0).+)$` just not match with 'test0'. Look the page example https://www.regextester.com/15.
