### ISSUE TITLE
Missing 'import copy'

### ISSUE THREAD

**Issue by timoalho** [hildogjr/KiCost#165]
Trying to run a BoM containing locally defined parts results in

    NameError: name 'copy' is not defined

and the program stops.

Using the attached file (renaming it to remove the .txt, github wouldn't let me attach an .xml -file) and running this gives the error:

    kicost -i KiCostimportbug.xml

[KiCostimportbug.xml.txt](https://github.com/xesscorp/KiCost/files/1686010/KiCostimportbug.xml.txt)

**Comment by hildogjr** [comment]
Fixed with commit ad925dcfe926dfc737d317c5df15e768a312d927, thanks Timo.
