### ISSUE TITLE
Excel file invalid when not performing distributors search.

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#194]
I run KiCOST while excluding all distributors to check that all grouping, part numbers, etc are ok before scraping.

I get the following error with Excel:

![image](https://user-images.githubusercontent.com/1504752/37253566-a08c2106-2533-11e8-978b-0902cf52fdb1.png)
[Translation: notepad encountered an invalid content in <<...>>.  Do you want to recover this file?  If the originator of the file is reliable, click Yes. ]

Excel can repair the file, so this is not extremely critical but it is of course a limitation.

I run kicost 1.42 like this:

> kicost -d 10 -i Manettes.xml -e digikey newark mouser farnell rs tme -o BOM_9309dummy.xlsx -var '^(.*)$' --overwrite -np 4 -f comment S1MN S1PN S2MN S2PN

The "Manettes.xml" file is enclosed:
[Manettes.zip](https://github.com/xesscorp/KiCost/files/1800427/Manettes.zip)

**Comment by hildogjr** [comment]
Hi @mdeweerd.
Are you using the last official release or the last GitHub code? (If last release, could you check with the last GitHub code? You can use `--no_scrape` instead of `--exclude digikey mouser ... allthem`).
I have some clue of the source of this error, but I could reproduce it on LibreOffice.

**Comment by hildogjr** [comment]
I did some improvement to deal with this specific case of just "assembly list".
[BOM_9309dummy.xlsx](https://github.com/xesscorp/KiCost/files/1801332/BOM_9309dummy.xlsx)
Check it in Excel, please.

**Comment by mdeweerd** [comment]
@hildogjr 
I was using the latest Github version & the file you joined in your last message opens in Excel without a problem.
Thank you.

**Comment by hildogjr** [comment]
So, fixed on merge https://github.com/xesscorp/KiCost/commit/3401830412545258815e7cd72aa9628d9f6958c9.
