### ISSUE TITLE
Variant field, desc field not ignored to group parts

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#195]
I run KiCost 1.42 like this on the attached file:

`kicost -d 10 -i Manettes.xml -e digikey newark mouser farnell rs tme -o BOM_3370dummy.xlsx -var '^(.*)$' --overwrite -np 4 --ignore_fields variant -f comment S1MN S1PN S2MN S2PN`

Notice that it is requested that the 'variants' field.
Yet the generated BOM file does not group the 1uF capacitors.

Also, the 1.41 documentation says:

> KiCost groups similar parts together and places their information on a single line of the generated spreadsheet. For parts to be grouped, they must:
> 
> - come from the same library (e.g., “device”),
> - be the same part (e.g., “R”),
> - have the same value (e.g., “10K” but note that this would not match “10000” or “10K0”), and
> - have the same footprint (e.g., “Resistors_SMD:R_0805_HandSoldering”).

It is not indicated that they should have the same description, the same variant, etc.

As you can see, the description field is empty.

When I request KiCost to ignore the "Desc" field to allow grouping on it, it fails:
`kicost -d 10 -i Manettes.xml -e digikey newark mouser farnell rs tme -o BOM_3734dummy.xlsx -var '^(.*)$' --overwrite -np 4 --ignore_fields desc variant -f comment S1MN S1PN S2MN S2PN`

> Traceback (most recent call last):
>   File "/usr/local/bin/kicost", line 9, in <module>
>     load_entry_point('kicost==0.1.42', 'console_scripts', 'kicost')()
>   File "/usr/local/lib/python2.7/dist-packages/kicost-0.1.42-py2.7.egg/kicost/__main__.py", line 260, in main
>     scrape_retries=args.retries, throttling_delay=args.throttling_delay)
>   File "/usr/local/lib/python2.7/dist-packages/kicost-0.1.42-py2.7.egg/kicost/kicost.py", line 262, in kicost
>     user_fields, '-'.join(variant) if len(variant)>1 else variant[0])
>   File "/usr/local/lib/python2.7/dist-packages/kicost-0.1.42-py2.7.egg/kicost/spreadsheet.py", line 174, in create_spreadsheet
>     parts, user_fields, collapse_refs)
>   File "/usr/local/lib/python2.7/dist-packages/kicost-0.1.42-py2.7.egg/kicost/spreadsheet.py", line 413, in add_globals_to_worksheet
>     desc_col = columns['desc']['col']
> KeyError: 'desc'

I would like to join all 1uF capacitors (in this example) on the same line.

[Manettes.zip](https://github.com/xesscorp/KiCost/files/1800522/Manettes.zip)
[Manettes_dummy.xlsx](https://github.com/xesscorp/KiCost/files/1800525/Manettes_dummy.xlsx)
[Manettes_expected.xlsx](https://github.com/xesscorp/KiCost/files/1800562/Manettes_expected.xlsx)

Edit:
I tried the new option  `--group_fields`  mentioned in #102:
`kicost -d 10 -i Manettes.xml -e digikey newark mouser farnell rs tme -o BOM_4636dummy.xlsx -var '^(.*)$' --overwrite -np 4  --group_fields desc variant -f comment S1MN S1PN S2MN S2PN`
(with group_fields, without ignore_fields) does not provide the expected result (grouping 1uF capacitors).

And
`kicost -d 10 -i Manettes.xml -e digikey newark mouser farnell rs tme -o BOM_4636dummy.xlsx -var '^(.*)$' --overwrite -np 4 --ignore_fields desc variant --group_fields desc variant -f comment S1MN S1PN S2MN S2PN`
(with ignore_fields and group_fields) generates an empty BOM.

**Comment by hildogjr** [comment]
@mdeweerd try the last modification in my personal branch (using the `--group_fields` and not the `--ignore_fields`). I am waiting @xesscorp do the v0.1.43, this fix will be in the v0.1.44 next month, when I want to, by default, merging the description, as your understanding of the user documentation (that I think is the correct).
`--ignore_fields` ignore the field on the file read function (as the original implementation), and it is not what you want.
`--group_fields` define the field value of each component of the group as the merged informations.

**Comment by hildogjr** [comment]
I used:

     kicost -i ./Manettes.xml -q -w --no_scrape -var '^(.*)$' -grp variant desc

**Comment by hildogjr** [comment]
@mdeweerd, I change more the code (for the next version, probably, but available on my Git). This version deal automatically with this situation, not need `-grp` of `--ignore_field`.

**Comment by mdeweerd** [comment]
Hi @hildogjr 
Thank you for the update - I may wait for the update to test this.
Kind regards
Mario

**Comment by mdeweerd** [comment]
Hi @hildogjr 
I tried the version from you hildogr/master today.
The command
 kicost -d 10 -i Manettes.xml -e digikey newark mouser farnell rs tme -o BOM_3501dummy.xlsx -var '^(.
*)$' --overwrite -np 4 -f comment S1MN S1PN S2MN S2PN

Generated this:
![image](https://user-images.githubusercontent.com/1504752/37723252-374c6554-2d2e-11e8-8737-c9b50ae8c75a.png)

- There are two lines with 470nF values (one starting with C10, the other starting with C7).
- C19 has the desc field filled in, the others have no desc field - so the other should "inherit" the desc field from C19, not be shown as an empty "desc".

Other lines have similar behaviors.

[Other "issue": when opening the excel file, the multiline fields appear as 1 line.  I have to enter the field and fake editing it to have two lines shown
Here is the XML file:
[ManettesXML.zip](https://github.com/xesscorp/KiCost/files/1834257/ManettesXML.zip)].

**Comment by hildogjr** [comment]
Missing just the `desc` multiline issue.

**Comment by hildogjr** [comment]
All fixed, was just a missing `[...]`.
Other tip: use `--no_scrape` instead of `-e digikey newark mouser farnell rs tme`
