### ISSUE TITLE
Part value auditing

### ISSUE THREAD

**Issue by xesscorp** [hildogjr/KiCost#2]
Parse device value (for R, C, L, similar where typically "value" field holds the value such as 100k, 4.7uF, 2 uH) and compare to distributor site value.  All match - green, some mismatch - yellow (warning), all mismatch - red.   Thought is to have some part information auditing while we're at it

**Comment by hildogjr** [comment]
This information may be added in the `Cat#` (of course, after implementation) of each distributor, to not add a lot of new columns. And using just the yellow and red background, green for no warning / error we may white background just as now.
