### ISSUE TITLE
It would be nice if the context shortcut shown in the video was documented

### ISSUE THREAD

**Issue by cb88** [hildogjr/KiCost#20]
Just for reference this is what I use... It runs kicost with debug level 1, overwrite and the file argument then drops out to the python shell.

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\xmlfile\shell\Open with KiCost]

[HKEY_CLASSES_ROOT\xmlfile\shell\Open with KiCost\command]
@="C:\\\\msys64\\\\mingw64\\\\bin\\\\python.exe -i -m  kicost -d 1 -w -i %1"
```

**Comment by xesscorp** [comment]
I added some text about doing that to the Usage section of the KiCost documentation.
