### ISSUE TITLE
Generate expanded list of refs C1,C2,C3 not C1-C3

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#209]
Some manufacturers with online BOM submission do not understand the short notation C1-C3 and require C1,C2,C3.

So it would be nice to have an option to output the second form.

I have asked one manufacturer to adapt 4 months ago and it is still not done by the manufacturer.  That manufacturer says that CAD tools output separate lines or comma separated lists so he is not inclined to change.

**Comment by hildogjr** [comment]
Replicated from #184.
On version 0.1.43 use `--no_collapse` in KiCost call.

**Comment by mdeweerd** [comment]
@hildogjr 
I overlooked this in the help as "collapse" did not trigger the right understanding.
Maybe the help text should change to something like:

> Do not collapse a list like C1,C2,C3 into C1-C3

Which seems more explicit in the help.

**Comment by mdeweerd** [comment]
It would also be nice (more readable, verifiable) if the references were ordered numerically (according to the last digits of the reference):

Prefer:
> C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C24,C25,C26,C27,C28,C29,C30,C31,C32,C33,C34,C35,C36,C37,C38,C39,C40,C41,C42,C43,C44,C45

over:
> C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C24,C25,C26,C27,C28,C29,C30,C31,C32,C33,C34,C35,C36,C37,C38,C39,C40,C41,C42,C43,C44,C45,C7,C8,C9

**Comment by hildogjr** [comment]
@mdeweerd , I agree. This is something related with the sort method of Python that by default do this.
