### ISSUE TITLE
Mouser scraping fails with "cannot convert string to float" because price tier returns "quote".

### ISSUE THREAD

**Issue by trcwm** [hildogjr/KiCost#234]
Mouser scraping fails with "cannot convert string to float" because price tier returns "quote".

For example, on the following part: https://www2.mouser.com/ProductDetail/STMicroelectronics/STM32F411RCT6?qs=sGAEpiMZZMvfpQN6QVmrfBwu%252bJWjhAvpke0TIYHKpxk%3d

An exception occurs on the following line of distributors/mouser/mouser.py on the line 61:
```
unit_price = float(re.sub('[^0-9.]', '', unit_price_tree.text))
price_tiers[qty] = unit_price
```

Attached is a test XML file that should produce the exception.

Running Python 3.6 on Windows with the latest KiCost code from the GIT repo. https://github.com/xesscorp/KiCost/commit/6004bbddcbd377fa97e9328e9369cd1616036108

[testbom.zip](https://github.com/xesscorp/KiCost/files/1892217/testbom.zip)

**Comment by hildogjr** [comment]
Thanks by reporting.
