### ISSUE TITLE
Alternate parts

### ISSUE THREAD

**Issue by volafh** [hildogjr/KiCost#236]
With a similar goal in mind like issue #17 I'd like to suggest the possibility of entering alternatives to parts. Especially when looking at generic passive components you might have tested several alternatives for your design and want to use the component with best availability.

There is something similar with Subparts. You can of course use subparts in order to automatically get storage and price of alternate parts and then manually delete the non-stocked or more expensive.

**Comment by hildogjr** [comment]
Something in this line could be:
1) Use more than one `manf#`cone in the design (e.g. manf# = PART1; PART5; PART4);
2) Set `ALIAS` variable (e.g. alias = 1; 3, in this example PART1 and PART4 are alias);
3) Create the spreadsheet as usual;
4) Create other spreadsheet page as 'minimum values of PART1 and PART4' or other rule or even some kind of 'combo select'/option select.

This is just a idea.
For now, I am trying to use time on the base feature as multiple currency #65 and bugs.

**Comment by hildogjr** [comment]
@mobilinkd, about the discussion in #17. This topic was closed by inactivity (the author never answer me with some discussion/guideline for implementation). 

The propose of use `|` as "or" is interesting, but we have to keep in mind that the different distributors could have best price in different `manf#` part that compose your selection. Therefore the spreadsheet have to deal with the best price (not the internal KiCost code), **this will ask for a new spreadsheet format**.

The work around is using the multipart options and select by your self.

I am re-opening this issue for new propose about, if you have some. But, for now, we have without people to fix the main recent issues of KiCost (https://forum.kicad.info/t/kicost-call-of-developers/13271), so I have to focus me time in keep KiCost operational (not working in #236, #17).
