### ISSUE TITLE
Group sub-parts

### ISSUE THREAD

**Issue by metropt** [hildogjr/KiCost#238]
Is it possible to group sub-parts?
I would like to group J3#4, J5#4 and J6#5.

![kicost](https://user-images.githubusercontent.com/764040/38878556-1a18d676-4259-11e8-8f00-13faa0c9d676.png)

Thank you

**Comment by hildogjr** [comment]
Yes.
Using the last code version here / commit, call KiCost as

    kicost .... -i -group_fileds value footprint

So the value and footprint column values will be grouped, if the parts have the same manf# (manF3 can't be asked to be grouped). In your case, may be not, cause yours manufactures part numbers are different, so are different parts to be purchased.

If have more problem, create a specific issue or re-open this adding the BoM file (if possible).
