### ISSUE TITLE
Board Qty field default value in .xlsx is not a valid number in LibreOffice

### ISSUE THREAD

**Issue by timoalho** [hildogjr/KiCost#265]
At least in LibreOffice 5.2.4.2, opening any .xlsx created by KiCost (for example, run any of the tests in the `tests` folder to produce an .xlsx), initially all quantity fields, costs etc are zero, except for Board Qty. After writing any number in the Board Qty field (including the default 100, just re-typing it is enough), all the quantities and costs are updated accordingly and the spreadsheet then works.

In a multi-BOM spreadsheet, changing quantities for one of the projects causes the quantities and costs related to that project *only* to be updated correctly (then changing the other also fixes that). So it's likely to be somehow related to the formatting of the field.

Last tested with commit SHA1 ca269388e9a521710bd1767902173612c6a5aaae, however this has been the case as long as I've used KiCost (a couple of years or so), and in all LibreOffice versions I've been through.

**Comment by hildogjr** [comment]
I ask about this once in the LibreOffice BugZilla, they adviser me that is just a configuration default NEVER.
In LibreOffice Calc check on:
Tools >> Options >>LibreOffice Calc >> Formula >> Recalculation on File Load
And change from "Never recalculate" to "Always" ou "Prompt".
