### ISSUE TITLE
Version 0.1.45 (not released) fails with SyntaxError on Py2.7

### ISSUE THREAD

**Issue by adamheinrich** [hildogjr/KiCost#267]
Hi,
I tried installing version 0.1.45 from master -- but it is not possible to run it because of `SyntaxError`:

```
$ sudo make install
# ...
Finished processing dependencies for kicost==0.1.45
$ kicost --version
Traceback (most recent call last):
  File "/usr/local/bin/kicost", line 11, in <module>
    load_entry_point('kicost==0.1.45', 'console_scripts', 'kicost')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/kicost-0.1.45-py2.7.egg/kicost/__main__.py", line 36, in <module>
    from .kicost import * # kicost core functions.
SyntaxError: can not delete variable 'scraping_progress' referenced in nested scope
```

Is there a workaround for this? The reason for trying v0.1.45 is that v0.1.44 fails to scrape data from Farnell ant TME.

Thank you!

**Comment by hildogjr** [comment]
I never used `make install` for Python packages, is this right? I could not reproduce this. (Witch OS or install method was used?)

**Comment by adamheinrich** [comment]
Why else would the Makefile be there? It simply runs `python setup.py install`.

I am using Ubuntu 18.04:

```
$ python --version
Python 2.7.15rc1
```

**Comment by adamheinrich** [comment]
Looks like it works when installing with `python3 setup.py install` instead (meaning that I don't get `SyntaxError` anymore, scraping still has problems).

For previous versions, I had no issues with Python 2.7 (also the code often imports from `__future__` so I assume there was no "official" switch to Python 3).

I am not a Python expert but it looks like the latest commits introduced incompatibility with Python 2.7 which should be addressed.

**Comment by hildogjr** [comment]
So it's Py2.7 error. We make huge change on the scrape code to avoid site ban. May be some workaround (different library needed for Py2.7).
The error is when use `kicost --version` or any other call? Just `kicost`; `kicost -i %FILE%` ...

**Comment by adamheinrich** [comment]
The error is with any call to `kicost`.

**Comment by hildogjr** [comment]
The commit #fa1d98f broke some pieces of code that are compatible Py2/3, @mmmaisel, @xesscorp. Did some fix, but still missing others.

**Comment by hildogjr** [comment]
Terminal version now working (despise the the final error about `del` that missing fix / work around).
The GUI also present some compatibility problems with Py2.

**Comment by mmmaisel** [comment]
When running kicost GUI with Python2, I get the following error:
```
  File "kicost/kicost_gui.py", line 1051, in kicost_gui
    frame = formKiCost(None)
  File "kicost/kicost_gui.py", line 247, in __init__
    self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 9718, in SetSizeHints
    return _core_.Window_SetSizeHints(*args, **kwargs)
TypeError: in method 'Window_SetSizeHints', expected argument 2 of type 'int'
```
I did some git bisect and that error first occured in commit #86da57f9 (older commits didn't run at all with errors before GUI creation). This looks like this error was either not found for a long time or that there was a regression in the Ubuntu 18.04 Python2 packages.

**Comment by hildogjr** [comment]
@adamheinrich, next month I am planning to release the next KiCost version with all the @mmmaisel implementations.
Did this bug still on actual GitHub code version?
