### ISSUE TITLE
Broken TME support

### ISSUE THREAD

**Issue by adamheinrich** [hildogjr/KiCost#268]
Hi, KiCost fails to get part information (pricing and stock levels) from TME, it only gets hyperlinks to TME catalogue:

![screenshot from 2018-06-09 10-34-38](https://user-images.githubusercontent.com/4582325/41189609-c799484e-6bd0-11e8-8fd0-acf670209397.png)

TME scraper first finds basic information (partnumber and link) on search page and then continues with AJAX request to get more details (stock, pricing). The observed behavior indicates that the AJAX request does not work anymore.

I did some investigation and it looks like the AJAX request was broken by 35b798e40066e9e4757670770da94fb2a98212c7 -- the new code introduced in the commit does not send the actual request in variable `data` anymore (the variable is left unused).

**Comment by hildogjr** [comment]
Fixed with #269
