### ISSUE TITLE
Premature Octopart integration

### ISSUE THREAD

**Issue by lod** [hildogjr/KiCost#318]
It looks like some work from the Octopart branch has slipped into master.

Specifically commit 6ee4b801016a08b08e15b452de0140e274ad5c4c
titled Fixed Output Folder

https://github.com/xesscorp/KiCost/commit/6ee4b801016a08b08e15b452de0140e274ad5c4c

It adds an import to .distributors.octopart which doesn't exist, calls functions from there and changes far more code than I would expect given the title.

I suggest reverting the merge.

**Comment by hildogjr** [comment]
Thanks to warning me @lod.
This branch is stopped on development, we will backup this branch and merge the new development.

Please try the branch named `octopart`, it is not merged yet because is missing some update on documentation.
