### ISSUE TITLE
After octopart update, partial partnumbers does not have a hit. 

### ISSUE THREAD

**Issue by skumfidus** [hildogjr/KiCost#319]
Feature / Enhancement request
Correct me if I'm wrong, but I believe that previously if Manf# field contained "TPS71733DRV" this could return a hit on "TPS71733DRVR". I presume the reel option (extra "R" at the end of the part number) might have been chosen because this was the cheapest option. This is a nice feature if you use a PCBA manufacture that can handle all kinds of tapes, reels, and trays. 

I'm running https://github.com/xesscorp/KiCost.git@octopart and now it requires part numbers to be exact matches to a specific hit on Octopart. It would be nice if Kicost was able to just choose the cheapest option that matches a search on the part number. Possibly adding to the file a field that tells if the part number listed is an exact match or a partial.

**Comment by hildogjr** [comment]
Before, the scrape module taken the most close matches which included "TPS71733DRVR" when asked by "TPS71733DRV".
We stay improving the new module. Please check your search at https://octopart.com to see the behavior (return always same package? test with differents partial partnumbers).

**Comment by hildogjr** [comment]
For implementation reference
https://octopart.com/api/docs/v3/rest-api#response-schemas-partsmatchrequest

@skumfidus, for some workaround until this enhancement, read the section "Part Number Filters" at
https://octopart.com/api/docs/v3/rest-api#notes-partoffer.prices

**Comment by hildogjr** [comment]
Merged with #346, it will be used the `match` API instead `part`.
