### ISSUE TITLE
Qty not respected for subparts

### ISSUE THREAD

**Issue by nickoe** [hildogjr/KiCost#327]
After fixing issue https://github.com/xesscorp/KiCost/issues/324 with e6b5a87ead990ed7b4b8db68dd84d4393a0637c3. There are still an issue left.

#### Issue / Problem report
1. The qty is not respected for each subpart. Test file https://github.com/xesscorp/KiCost/files/2439992/subpartbom.txt

This bug is created with the motivation from https://github.com/xesscorp/KiCost/issues/324#issuecomment-426830132

**Comment by hildogjr** [comment]
This limitation is already known in the older version but needs to be fix in Octopart API.

**Comment by hildogjr** [comment]
@nickoe, test this fix. But you still to use the blank at 'manf#'

**Comment by hildogjr** [comment]
I added also the warning tip when detected the  ambiguous case.

**Comment by nickoe** [comment]
I have just tesed master including your commit. I can confirm that it works as expected and it also erros on mismatch between part fields. Everything is good now. Thanks. :)

**Comment by hildogjr** [comment]
If you miss some message or tip that could help users. Give us a hit, we need the users feedback.

**Comment by nickoe** [comment]
As it seems to work as expected now I don't see anything missing. One could add a note in the doc that for multiple subparts they are mapped one to one, hence one may need to add empty fields. But as that is an error thrown by the script they user will catch it anyways.
