### ISSUE TITLE
Better collapse in multiprojects case

### ISSUE THREAD

**Issue by hildogjr** [hildogjr/KiCost#328]
Better group in multiprojects case.
In project 0: R1, R3, R4, R5
In project 1: R11, R15, R2

These all with same `manf#` could be grouped as

    proj0:R1,R3-R5
    proj1:R2,R11,R15

Current is:

    proj0:R1,proj0:R3,proj0:R4,proj0:R5,proj1:R2,proj1:R11,proj1:R15

**Comment by hildogjr** [comment]
Pumping up as low level bug.
It will need a fix in the group routine.

**Comment by set-soft** [comment]
Hi @hildogjr !
Take a look at the multiproject test (multipart1+2.xlsx) I think this is what you wanted to do.

**Comment by hildogjr** [comment]
By the check case `multipart1+2.csv` file appear to be exactly what I though. For example:

```
"prj0:SW1-SW3,SW5-SW9
prj1:SW1-SW3,SW5-SW9", ...
```

I didn't test yet due some Kitspace unavailability.
