### ISSUE TITLE
installing kicost

### ISSUE THREAD

**Issue by Arunmaran** [hildogjr/KiCost#33]
Hi All,
When i run a command "$ easy_install kicost" or 'pip install kicost' to  install kicost it shows syntax error in command line. 

I am very new to python. So some one guide me in solving this problem.

Regards,
Arun

**Comment by xesscorp** [comment]
Hi, Arun. Did you solve this problem. If not, what error message did you receive?

**Comment by Arunmaran** [comment]
Hi,

Issue Solved. Thanks for the reply.
"easy install" didn't worked out, but PIP command worked.
May be the Kicost directory should be changed i think,whereas pip is downloading and installing. 
So it worked i think.
