### ISSUE TITLE
TypeError: unbound method query_part_info() must be called with dist_local_template instance as first argument (got list instance instead)

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#332]
KiCost 1.0.4 produces a fatal error (see title).

Tried with simple "kicost -i demo.xml" .
Bom is in the ZIP: [demo.zip](https://github.com/xesscorp/KiCost/files/2499435/demo.zip)

> Traceback (most recent call last):
>   File "/usr/local/bin/kicost", line 9, in <module>
>     load_entry_point('kicost==1.0.4', 'console_scripts', 'kicost')()
>   File "/usr/local/lib/python2.7/dist-packages/kicost-1.0.4-py2.7.egg/kicost/__main__.py", line 257, in main
>     dist_list=dist_list, currency=args.currency)
>   File "/usr/local/lib/python2.7/dist-packages/kicost-1.0.4-py2.7.egg/kicost/kicost.py", line 191, in kicost
>     dist_local_template.query_part_info(parts, distributor_dict, currency)
> TypeError: unbound method query_part_info() must be called with dist_local_template instance as first argument (got list instance instead)

**Comment by FabioVasconcelos22** [comment]
I got the same problem in version 1.0.3!

**Comment by kuoyaoming93** [comment]
I got the same problem with Centos 7 (version 1.0.3)!

**Comment by hildogjr** [comment]
This appear to be a Python 2 issue, as shown at @mdeweerd log. In Python 3 is normal.

**Comment by mdeweerd** [comment]
I confirm that switching to python 3 and adding a octopart api key of myself works.

**Comment by hildogjr** [comment]
Thanks @mdeweerd.
There is 2 issues now to be fix:
1. This Py2 compatibility;
2. The key, at least have to be a warning to the user that the current of is expired.

**Comment by 01tot10** [comment]
Hey peoples! 
I was experiencing similar issues than the OP of this thread and just wanted to report the full outcome.

First got this:
>> TypeError: unbound method query_part_info() must be called with dist_local_template instance as first argument (got list instance instead)

As suggested, switching to python3 helped.

Then got this:
>> Exception: Octopart KEY invalid, registre one at "https://www.octopart.com".

As suggested, I registered for an apiKey at octopart, and hard-wrote my apiKey to all instances of 'apiKey=??' in "dist_octopart.py".

After this, I got KiCost to run without issues, but in the output .xlsx, all the prices fields (Unit$, Ext$) are $0.00. The correct man#'s have been parsed succesfully, and Octopart seems to return correct available quantities (Avail), so the API seems to be somewhat working, but only partially.

I just wanted to ask if this is something other's might have also experienced, and if there's a fix?

Running Ubuntu 18.04 and Python3.

**Comment by hildogjr** [comment]
@01tot10, please check #331.

**Comment by 01tot10** [comment]
> @01tot10, please check #331.
Hey hildogjr, thank you for the heads-up. I did have a look at the topic also yesterday, but wasn't sure if the behaviour was the same that I was experiencing since I didn't get any error messages that were mentioned on the thread.

Anyways, as of this morning my Octopart key has also been assigned the status 'Inactive pending Octopart approval', so I guess I'm also in the same train as you are.

"Sad".

Anyways, thanks alot for the swift reply and help!
