### ISSUE TITLE
Octopart KEY

### ISSUE THREAD

**Issue by gmsotavio** [hildogjr/KiCost#345]
It is my first issue on KiCost. First of all, thanks for XESS Corp. @xesscorp by its valuable effort to release KiCost as an open source tool for KiCad users.

My problem is related to Octopart API Key. I've created a simple KiCad schematic to test KiCost, with only 4 parts. Afterward, I've generated a BOM in XML format and used it as input for KiCost:

`kicost -i kicost_test_project.xml -w  `

The output:
`Octopart KEY not informed.`

Ok. I've not found an option to pass my key through the command line. Then I've filled the key in GUI and used the `--user` parameter in the command line:

`kicost -i kicost_test_project.xml -w --user` which resulted in the following error

`AttributeError: 'formKiCost' object has no attribute 'm_textCtrlextracmd'`

What may I have been doing wrong ? KiCost is working?

I'm using the python3.5 within a virtual environment and the latest release of KiCost, with wxPython for GTK2. I got the same error using python 2.7.

Otavio

**Comment by hildogjr** [comment]
@gmsotavio, please use the workaround of last message in https://github.com/xesscorp/KiCost/issues/344.
The GUi keeps the KEY in a configuration field but we didn't made a method to save it on the CLI.
