### ISSUE TITLE
Add CI distribution

### ISSUE THREAD

**Issue by hildogjr** [hildogjr/KiCost#348]
Could be interesting add a continuous distribution system such
https://stackoverflow.com/questions/48681816/upload-to-pypi-from-gitlab-pipelines
this will also fix #232 

@devbisme ?

**Comment by nevercast** [comment]
FWIW I know Travis (free for OSS projects) can deploy artifacts to Github. I am not aware of the details though. https://docs.travis-ci.com/user/deployment/releases/

**Comment by hildogjr** [comment]
I will give a look after the new API. Could be interesting some help of a more experiment user.

**Comment by hildogjr** [comment]
Almost fix. I am closing this for now.
