### ISSUE TITLE
Non-ASCII character '\xc3' in file ... but no encoding declared

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#350]
SyntaxError: Non-ASCII character '\xc3' in file /usr/lib/python2.7/site-packages/kicost-2.0-py2.7.egg/kicost/__main__.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Solution:  Add a header line like 

`# -*- coding: utf-8 -*-`

**Comment by hildogjr** [comment]
Thanks for the suggestion.
Are you able to still using KiCost at Python 2? In last code changes I was using my energy to the feature and less to the Py2 compatibility.

**Comment by mdeweerd** [comment]
Apparently there were too many ongoing changes so I reverted to an earlier version

**Comment by hildogjr** [comment]
The main branch here is in development and not functional yet.
The last, frozen, functional branch is Octopart.

**Comment by hildogjr** [comment]
Fixed in main branch
