### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#351]
- \*sorted(...)  results in invalid syntax
- `print('{} = '.format(f), end=' ')` gives invalid syntax (line 231, kicost.py) on th e"=" symbol for end
  => replaced with `print '{} = '.format(f),`
```
from urllib.parse import quote_plus as urlquote
ImportError: No module named parse
```
Replace with
```
try:
    from urllib.parse import quote_plus as urlquote
except ImportError:
     from urllib import quote_plus as urlquote
```

-
`from .dist_local_template import dist_local_templates`
replace with 
`from .dist_local_template import dist_local_template`

- kicost_gui.py
    `from .distributors import init_distributor_dic`

	-> commented  
	   `from .kicost_gui import *` etc.
	   as I am not using the gui.

-     
`dist_list.remove(d)
ValueError: list.remove(x): x not in list`

I had an invalid distributor in the exception list - I added a try: except: pass arround the remove.

-
`  File "kicost.py", line 215, in kicost
    dist_local_template.query_part_info(parts, distributor_dict, currency)
TypeError: unbound method query_part_info() must be called with dist_local_template instance as first argument (got list instance instead)
`
Stuck here.

Moved to python3:
```
    if len(octopart_query) == OCTOPART_MAX_PARTBYQUERY:
NameError: name 'OCTOPART_MAX_PARTBYQUERY' is not defined
```

My workaround: Added `OCTOPART_MAX_PARTBYQUERY = 16` to head.

```
partinfo_kitspace.py", line 285, in get_part_info
    results = dist_octopart.query(query, apiKey)
NameError: name 'dist_octopart' is not defined
```

-> Stuck here (no "def dist_octopart" found)

### Final solution
Rolled back to  `git checkout  b567f40`

**Comment by hildogjr** [comment]
@mdeweerd, this fix is related with the [Octopart branch](https://github.com/xesscorp/KiCost/tree/octopart) that is been decrepited.
Now, we are moving (and needing help) to Partinfo API #346 to provide better API to user, not dependent to Octopart Key. For now, since Python2 is in retire countdown, I am not using time for Py2 compatibility.

**Comment by mdeweerd** [comment]
Hi
I understand - I upgraded my KiCost installation as I wanted to check how evolutions were going, but then it was dysfunctionnal, even when disabling all distributors.
I am quite busy myself, I always hope that sharing difficulties and workaround is a help to the team.
I am not so much using pull requests, etc.
I tried to make some contributions in the past, but KiCost was evolving too fast.

**Comment by hildogjr** [comment]
The focus of KiCost now is make it work with PartInfo API, not being dependent of Octopart KEY anymore.

As secondary issues, we have: improve the GUI, improve the installation to create a program icon and KiCad plugin at Pcbnew, and issues if documentation.


Make pull-request by the github web interface is straightforward: you upload your code / change to you user repository version, submit the pull-request, the KiCost administrator check and merge it to the main.

**Comment by mdeweerd** [comment]
With regards to the code: I know how to pull/push - as said KiCost evolves too much fort that.  I had quite some changes in a fork I have now deleted that became incompatible by the time it was ready for sharing.

Some brainstorming suggestion for the logo.

![image](https://user-images.githubusercontent.com/1504752/56837351-5dc4fb00-687a-11e9-87fe-0c741f563ccf.png)

I'll think about documentation/plugin - share my method of using KiCost.

**Comment by hildogjr** [comment]
Unfortunately the first step of KiCost (get the information through API / scrape) is being re-write.
The spreadsheet have few improvements: fix Digikey "txt importer" and its was add some checks to avoid misunderstood in the purchase act.

The icon:
I liked it, main for a logo. Maybe I give some more attention (uppercase) to the "C / €".
The icon should fit as shortcut in the desktop / start menu and the program window. For now, we I are using https://github.com/xesscorp/KiCost/blob/master/kicost/kicost.ico
I need a 16x16 icon version for use as KiCad menu plugin. I was thinking: some coin with "Ki" inside and the border/shadow making the "C".

**Comment by mdeweerd** [comment]
Icons can be considered minimum 32x32 nowadays.
It could look like a coin rather than a bill.
Here is a another brainstorm suggestion - the SVG is in the zip.
![image](https://user-images.githubusercontent.com/1504752/56870803-4110fa80-6a15-11e9-9ea2-0f4a921ff5b8.png)
[KicostLogoSuggestion.zip](https://github.com/xesscorp/KiCost/files/3125561/KicostLogoSuggestion.zip)
With some color:
![image](https://user-images.githubusercontent.com/1504752/56870897-a1ed0280-6a16-11e9-9df3-3210a9cb0545.png)

**Comment by hildogjr** [comment]
The KiCad documentation recommends a 26x26px:
http://docs.kicad-pcb.org/doxygen/md_Documentation_development_pcbnew-plugins.html

I was think some compact for the coin icon:
![compact](https://user-images.githubusercontent.com/2211474/56871161-28dab480-69f0-11e9-9d31-78b0d81ecfbb.png)
also that the border could remember a coin, in perspective.
![compact2](https://user-images.githubusercontent.com/2211474/56871181-722b0400-69f0-11e9-8b9a-af9c0fdb5ff7.png)

**Comment by hildogjr** [comment]
Actual icon used:
![icon](https://user-images.githubusercontent.com/2211474/56871281-ffbb2380-69f1-11e9-8268-5ac166636c7c.png)

**Comment by mdeweerd** [comment]
I like the dime in perspective.  The "K$" should be a bit bigger on the coin so that it is more readable at 24x24 - similar to the flat K$.

**Comment by hildogjr** [comment]
@mdeweerd, totally agree. The perspective dime cold be used to derivate a shadow "=", making an ambiguous "C" / "€" symbol and over the "K$".
(I am not good with graphics, so mine is just a draft).
The KiCost logo proposed (black letters with currency symbols) will be not visible at black/dark desktops or KiCad theme (I think this is in them roadmap). The green bill solve this problem, my propose is merge these ideas, with you agree.

**Comment by mdeweerd** [comment]
I think that the two horizontal bars are a good suggestion of the other currency symbols - there is no need to overload the logo/icon.
I only now understand the suggestion of the € in the flat logo - I think this can be reminded in the same way by having a darker border/background to represent the € symbol.

**Comment by hildogjr** [comment]
@mdeweerd, could provide this 2 icons version? The coin (`kicost_coin.svg`/png) and the bank note (`kicost.svg`).

**Comment by mdeweerd** [comment]
HI
I saw that you assigned me this and I will do something, but I have some other priorities.
Please be patient ;-).

**Comment by hildogjr** [comment]
No problem.
I am concerned now to make the new API before release and found someone (in KiCad forum) to help with the Windows / GUI issues.

**Comment by mdeweerd** [comment]
Hi

I made some time to work on the logo.

These are the 24x24 and 512x512 versions.
I think that the 24x24 version is acceptable.

![kicost_dime24](https://user-images.githubusercontent.com/1504752/63781011-5c1f4880-c8e9-11e9-99dd-43b61066124c.png)
![kicost_dime512](https://user-images.githubusercontent.com/1504752/63781012-5c1f4880-c8e9-11e9-8285-96b219358553.png)

This is the SVG in a ZIP file:
[Kicost_Dime.zip](https://github.com/xesscorp/KiCost/files/3546701/Kicost_Dime.zip)

**Comment by mdeweerd** [comment]
Almost 4 years - closing.
