### ISSUE TITLE
Keep DNP/NOPOP in output with Qty=0 and column DNP

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#358]
To make sure that no component was forgotten during the analysis, it is common practice to also list the DNP/NOPOP components in the BOM file on separate lines with quantity 0 and a DNP/NOPOP mention somewhere.

So the feature would be to group all DNP/NOPOP components at the end of the list - with Qty 0 and possibly with the pricing info (not required).
Qty 0 is already an indication that the component is not mounted, but an extra DNP column may be usefull for some.

**Comment by hildogjr** [comment]
First study:
This should be activated by a `--show_dnp` and may be required some changes in the group routines. Also some implementation to make sure that will be show at the end of the spreadsheet.
(Files to be modified: each BOM read module, spreadsheet.py order and group routine).


A important question is: if one DNP part is grouped with other of same kind but that have to be assembled?

**Comment by hildogjr** [comment]
Needed #359 fix for not workaround.

**Comment by mdeweerd** [comment]
Stale, closing (limiting my issue backlog).
