### ISSUE TITLE
list index out of range - when using dist# and kicost:dist:pricing 

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#368]
KiCost version 1.1.1 (installed using pip)

I get error
  File "/usr/lib/python3.7/site-packages/kicost/distributors/api_partinfo_kitspace.py", line 300, in query_part_info
    part_code_dist = list({k for k, v in dist_xlate.items() if v == part_catalogue_code_dist})[0]
IndexError: list index out of range

I found that this is because I have kicost:dist:pricing for one component and dist# for another component.

I enclose an example which fails and two variants of the example that pass.
The executed commands are in "tests.sh", the log is in tests.log.

**Comment by mdeweerd** [comment]
Hi Hildago

I was convinced that I attached this example:
[testcase.zip](https://github.com/xesscorp/KiCost/files/3566530/testcase.zip)

Hopefully it is ok for you.

**Comment by hildogjr** [comment]
It was due the "tme#". The new API Kitspace doesn't support it and it was trying to use.
Now the code check if the code is supported before use.
