### ISSUE TITLE
DigiKey part numbers target Digi-Reel

### ISSUE THREAD

**Issue by romain145** [hildogjr/KiCost#376]
The DigiKey part numbers returned are a mix between cut-tape and Digi-Reel.
The difference is that Digi-Reel adds cost (typically $7.00) to each part number.
Is there a way to specify a preference to KiCost or to the Partinfo/Octopart API?

**Comment by hildogjr** [comment]
Give us a file example to help track the issue and provide the KiCost version `kicost --version` /  `kicost --info`.

**Comment by romain145** [comment]
```
Z:\git\github\KiCost>kicost --version
KiCost v.1.1.3
```

See attached [esc.zip](https://github.com/xesscorp/KiCost/files/3922083/esc.zip)

DigiKey references containing "HDKR" are Digi-Reel.
DigiKey references containing "HCT" are Cut-Tape.

**Comment by hildogjr** [comment]
Could you be more specific?
Which part are related to the problem? (Are all parts?) What the problem cause in the spreadsheet? (I image that change the price tiers in the balloon and the price function).
I have little time between my jobs to catch the issues, specific descriptions could help.

**Comment by romain145** [comment]
Sure!
The part numbers are a mix of Cut-Tape and Digi-Reel as shown below:

![image](https://user-images.githubusercontent.com/4060945/70396603-d55f2900-1a0a-11ea-8c63-68b6820a5d8d.png)

When searching for the part on Octopart, it returns both options. not sure how Partinfo picks one and return it to KiCost?

![image](https://user-images.githubusercontent.com/4060945/70396646-1f480f00-1a0b-11ea-9467-93153e8365b3.png)

**Comment by ghost** [comment]
I can confirm this issue and I also have a fix: #384

**Comment by hildogjr** [comment]
@romain145, I just tested the fix provided by @fri-sch, appear fine and without any collateral. Could you confirm that fix the reported case? I intend to release it.

I just concerned because it check by Stock numbers that ends with "DKR-ND", I am checking some user case to be sure that covers all Digikey Reels (it appear be the only information that tha API give us and differentiates the parts).

**Comment by ghost** [comment]
> I just concerned because it check by Stock numbers that ends with "DKR-ND", I am checking some user case to be sure that covers all Digikey Reels (it appear be the only information that tha API give us and differentiates the parts).

Your concerns are justified. I just found out, that the 'DKR-ND' ending doesn't cover all DigiKey reels. It seems like only capacitors, resistors, etc. are named like this. Other components, like ICs have '-6-ND' for the reels and '-1-ND' for the cut-tape. I don't know if there are other schemes for other kinds of parts.

Here's another fix: #385

**Comment by hildogjr** [comment]
Thanks by check @fri-sch, I merged your solution, I just will improve to add this configuration at the Digikey profile of KiCost before the official release.
I also had add your name to official contribution history https://github.com/xesscorp/KiCost/blob/master/kicost/AUTHORS.rst (this is displayed at the GUI interface and help page).

**Comment by hildogjr** [comment]
There still some inconsistencies about the link and stock code.
