### ISSUE TITLE
Broken documentation link in README

### ISSUE THREAD

**Issue by johnthagen** [hildogjr/KiCost#377]
#### Issue / Problem report

https://github.com/xesscorp/KiCost#kicost

> Documentation: https://xesscorp.github.io/KiCost

This link on the README returns a 404.

**Comment by hildogjr** [comment]
This problem is related to the [Makefile](https://github.com/xesscorp/KiCost/blob/master/Makefile), it I big documentation issue. I don't known how to fix it.

**Comment by xesscorp** [comment]
I fixed this. To rebuild the documentation, just go into the `docs` folder and run `make singlehtml`. Then just commit the changes and push them up here.
