### ISSUE TITLE
KiCost it! button not working and there's no output

### ISSUE THREAD

**Issue by MohamedElwazzan** [hildogjr/KiCost#388]
Kicost v.1.1.3
GUI
I've installed Kicost two months ago and it was working well
today I decide to generate spreadsheet  but unfortunately without any reason it just not responding to the "KiCost it!" button.
I've tried to use an old xml file that worked before but still the same problem 
Also I tried to reinstall it and figure out if there's any error log or something but I have no idea.

Now I've tried commands and I got this error
" Exception: One of the internal Kitspace services may experiencing problems. Contact the Kitspace support."

Best Regards

**Comment by hildogjr** [comment]
thanks by reporting, I have tested it now and I didn't get this message. it could had be some temporary unavailable of the [Kispace server](https://opencollective.com/kitspace).

Please, check it again today.

**Comment by MohamedElwazzan** [comment]
Thanks for your reply.
I've checked and it works well now 
yes maybe as you said it was just a temporary problem with Kispace server and now it works again 
Regards,

**Comment by hildogjr** [comment]
There is a plan to add multiple sources to KiCost (directly Digikey, Mouse through them API) but it still in a plan.
