### ISSUE TITLE
Unable to display tme and arrow in the menu.

### ISSUE THREAD

**Issue by AlkalineZN** [hildogjr/KiCost#390]
Hello 
I'm runnig Kicost 1.1.3 on windows 10  Python 2.7

The program works and I can get the bon with the costs but I can not insert arrow and tme as suppliers.
In the Kicost gui menu they are not even selectable
![kicost](https://user-images.githubusercontent.com/61738726/77420263-03098b80-6dca-11ea-9992-2d6e06a37714.jpg)
Do you have any suggestions?

Kind regards

**Comment by hildogjr** [comment]
I just had upload and release the fix https://pypi.org/project/kicost/
Re-install and execute `kicost --setup` before the first use (this will create the KiCad-KiCost better integration).
