### ISSUE TITLE
Cannot paste BOM on Farnell

### ISSUE THREAD

**Issue by romain145** [hildogjr/KiCost#393]
The generated list of parts to purchase is not in a format accepted by Farnell Quick-Buy (also called Quick-Paste) tool.

The list of parts generated in the spreadsheet doe snot have the comma or tab separators:

![image](https://user-images.githubusercontent.com/4060945/82140536-80cc9f00-982f-11ea-82e4-e3b87aedc57a.png)

![image](https://user-images.githubusercontent.com/4060945/82140543-93df6f00-982f-11ea-9040-730297e0498c.png)

Using Kicost v1.1.4.

**Comment by hildogjr** [comment]
I don't have a Farnell account. Please, provide me the correct format/sequence to I make the internal chances (if possible a XML with 2 or 3 parts and the expected values to import, to make possible to validate).

**Comment by romain145** [comment]
The format is here: 
https://export.farnell.com/quick-order?isQuickPaste=true

Example:
'4340504, 10, Need for project X', CUST1234
'4333974, 100, Order by Bob'

**Comment by hildogjr** [comment]
So: stock code, quantity, description, user fields?

Are the user fields (optional) really used/stamped at the delivered package?

**Comment by romain145** [comment]
Yes they are and it's really handy :)
The parts reference get printed on the bag:

![20200517_161550](https://user-images.githubusercontent.com/4060945/82150878-d4ec7900-9859-11ea-999b-e153da438a23.jpg)

**Comment by hildogjr** [comment]
This will need some lines of code. Could you give more information about específica this: maximum fields allowed (I suppose that is printed in a by-line format), maximum length allowed (characters allowed at the line), is the some not allowed characters,...

The description (e.g "ordered by Bob"in your example) is printed in other part of the stamp?

Achieve the first three field information is easy in the actual code. I want up already fix the full possibility.

**Comment by romain145** [comment]
Maximum characters allowed for line comment and part number seems to be 30 (including commas).
Usually I leave the line comment empty by putting a double comma like this:
`2211140, 10,, CUST1234,CUST1234,CUST1234,CUST1234,CUST1234,`

Note that if the part number is longer than 30 characters, it gets truncated down to 30 like this:
![image](https://user-images.githubusercontent.com/4060945/82152068-2e0adb80-985f-11ea-92d7-f525a7e2a50a.png)
However if the field is longer than 65 the line is ignored.

Special characters are supported, except for ' and " which are parsed out. Hope this helps :)

**Comment by hildogjr** [comment]
Fix the order, missing the implementation of the user custoom fields.
@romain145 , please check it.
It will be helpful if you could also give some try on other distributors / link the link for direct importation (for example, Digikey is https://www.digikey.com/ordering/shoppingcart)

**Comment by hildogjr** [comment]
Next step will be include the 'desc' (description) and others custom fields, all displayed at the spradsheet.
Could you provide me a XML example and the intended table list?

**Comment by hildogjr** [comment]
Now, for default Farnell and Newark add all the user fields as your example for custom fields.

You can edit for just one specific in the `distributors_info.py` file.

**Comment by hildogjr** [comment]
The feature request is duplicated from #394
