### ISSUE TITLE
Multipart component - pricing, datasheets, otherfields

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#394]
I am using "KiCost v.1.1.2"

For a Fuse holder, I defined the holder, the fuse and the clip cover.

![image](https://user-images.githubusercontent.com/1504752/82358737-3bfb6080-9a07-11ea-991f-083381a3f0b2.png)

In the Excel file, I have three lines (ok), with the same pricing (nok), and the other fields are not "split" across the excel lines (desc, S1MN,S2PN,S1PN).

![image](https://user-images.githubusercontent.com/1504752/82358661-1e2dfb80-9a07-11ea-9bea-18f3d49cdeb2.png)

I also tried to add an empty price (kicost:we:pricing=1:EUR0.07;;1:EUR0.03) but that resulted in a fatal error.

Here is the test case:
[multipart.zip](https://github.com/xesscorp/KiCost/files/4652208/multipart.zip)

I did not test the most recent version as I do not want to break my setup at this moment.

**Comment by hildogjr** [comment]
Personal distributors (for now) doesn't allow multiparts.

**Comment by mdeweerd** [comment]
Stale, closing (limiting my issue backlog).
