### ISSUE TITLE
Tests rely on Kitspace - uses resources

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#406]
Now that the CI is running and verifying tests (Example: https://travis-ci.com/github/xesscorp/KiCost/jobs/339851223 ) , the following error occurs:
"Exception: One of the internal Kitspace services may experiencing problems. Contact the Kitspace support."

I guess some updates to the tests are needed...  Possibly generate BOMs without checking kitspace for the moment?

**Comment by hildogjr** [comment]
Yes. By using the `kicost --no_price` directive. As far I saw, the golden files check the global part of the spreadsheet only.
I was thinking exactly in this case yesterday.
