### ISSUE TITLE
Text improvement

### ISSUE THREAD

**Issue by leoheck** [hildogjr/KiCost#411]
Using version 1.1.5

I would like to suggest replace this text
From `Convert to ODS` to `Save as .ods `

Also, this checkbox could be removed by saving selecting it by the file extension
Since using `file.xlsx` with `Convert to ODS` makes no sense.
For that work, I would suggest replacing the 
`Spreadsheet output file` with `Spreadsheet output file (.xlsx or .ods)`

**Comment by hildogjr** [comment]
There is a issue #361 for a GUI re-manufacture. (Yes, it is been needed).
Please up your ideias.

**Comment by hildogjr** [comment]
Merged in #361
