### ISSUE TITLE
Kicost not run

### ISSUE THREAD

**Issue by AlkalineZN** [hildogjr/KiCost#428]
Hi
I am trying to get the file processed by Kicost with no success.

The program seems to do absolutely nothing.
![kicost not run](https://user-images.githubusercontent.com/61738726/101205171-9db2ad80-366d-11eb-953f-1c3496292f8d.jpg)

I tried to install the program on another pc and I have the same error

**Comment by hildogjr** [comment]
Possible duplicated from https://github.com/xesscorp/KiCost/issues/412
