### ISSUE TITLE
Part Number variant

### ISSUE THREAD

**Issue by metropt** [hildogjr/KiCost#429]
Hi,

Is it possible to use variant to select a part number? Per example a capacitor that could have two different values if it is --variant DC5V or --variant DC12V

Thank you

**Comment by hildogjr** [comment]
Yes: check the "Custom Part Data" at https://xess.com/KiCost/docs/_build/singlehtml/index.html

If you are using KiCad, use two specif fields:
`kicost:DC5V:MPN` or `kicost:DC5V:manf#` or ...
and 
`kicost:DC12V:MPN` or `kicost:DC12V:manf#` or ...


If you are using Eagle, Altium, Proteus or other EDA with CSV based output, the column should reflect the same as above.

To generate the `*.xlsx` file use the `kicost --variant` call as the "Examples" into the "Usage" section of the before link.
