### ISSUE TITLE
Component rows in spreadsheet refer to "BoardQty" even when multiple xml files as input and the numbers are "BoardQty0" and "BoardQty1"

### ISSUE THREAD

**Issue by sliedes** [hildogjr/KiCost#465]
#### Issue / Problem report

KiCost v 1.1.5

I used the command `kicost --gui proj1.xml proj2.xml` to generate a common spreadsheet for two separate projects. The spreadsheet looks superficially correct; however the Qty fields have formulas like `"=CEILING.XCL(BoardQty*17;1)"`. The variables set in the are BoardQty0 and BoardQty1, and BoardQty is, I believe, not set anywhere. The correct formula in my case would have been `BoardQty0*15 + BoardQty1*2`.

**Comment by set-soft** [comment]
Hi @sliedes !
My fix for the qtys was incomplete, now I think it should show correct ammounts and also keep track of different board ammounts.
Can you check if it is working for you?
