### ISSUE TITLE
1.1.4 KiCost stalling and not loading component data.

### ISSUE THREAD

**Issue by BillyPocketNC** [hildogjr/KiCost#479]
I hope this is helpful for other KiCost users when KiCost stalls and will not get prices on components.
I edited the api_partinfo_kitspace.py line 69 to get KiCost working.

Before: QUERY_URL = 'https://dev-partinfo.kitspace.org/graphql'
After: QUERY_URL = 'https://partinfo.kitspace.org/graphql'

Found fix here, but there is not a new release to fix this problem yet.

partinfo.kitspace.org is pingable - maybe we need to remove the "dev-" part!

_Originally posted by @mdeweerd in https://github.com/xesscorp/KiCost/issues/457#issuecomment-814271394_

**Comment by mdeweerd** [comment]
It's not clear what is going on because it was also requested to not use 'https://partinfo.kitspace.org/graphql' which is in fact cached data that is never updated.

**Comment by set-soft** [comment]
Yes KitSpace maintainer asked not to use the cache server.

I sent an email to @kasbah he will tell us what's the problem.

**Comment by kasbah** [comment]
That's right, the main partinfo API (without dev-) is the one used for the component popups on https://kitspace.org itself. We don't use any of the pricing info there so we cache it aggressively. It's not going to be very useful to get current prices.

**Comment by jhaand** [comment]
I'm glad to see that Kicost works again as expected.

**Comment by kasbah** [comment]
The main issue with it stopping working is that we have a limit of 5000 Octopart requests per month. This is shared between Kitspace, KiCost and HorizonEDA use. If you we want to contribute towards increasing the limit you can do so through [our Open Collective](https://opencollective.com/kitspace).
