### ISSUE TITLE
Component grouping - limiting the hash calculation to known fields?

### ISSUE THREAD

**Issue by oliviermartin** [hildogjr/KiCost#48]
_For the context:_ Before I discovered KiCost, I started to work on a basic solution - just adding a set of known 6+ fields to every components such as 'Digikey PN', 'DigiKey Price x1', 'DigiKey Price x1000', 'Mouser PN', etc
My BOM is not huge but long enough to get bored after adding these fields for the first 5 components. At that time I thought it would be a nice project to automate the process. 
Luckily before I started to work on it I found your project! After fixing the issue https://github.com/xesscorp/KiCost/pull/46, the project has been working fine with my BOM.

Except... I found that KiCost was not able to group my 4 10K resistors together. It only managed to do 2 pairs of 10K resistor. 
I started to debug KiCost `get_part_groups()` and I found this code:

```
        # Take the field keys and values of each part and create a hash.
        # Use the hash as the key to a dictionary that stores lists of
        # part references that have identical field values. The important fields
        # are the reference prefix ('R', 'C', etc.), value, and footprint.
        # Don't use the manufacturer's part number when calculating the hash!
        # Also, don't use any fields with SEPRTR in the label because that indicates
        # a field used by a specific tool (including kicost).
        hash_fields = {k: fields[k] for k in fields if k not in ('manf#','manf') and SEPRTR not in k}
```

My set of component is this one:

```
'R5': {u'footprint': 'Resistors_SMD:R_0603_HandSoldering', u'libpart': 'device:R', 'reference': 'R', 'value': '10K', 'manf#': 'ERJ-3EKF1002V'},
'R6': {u'footprint': 'Resistors_SMD:R_0603_HandSoldering', u'libpart': 'device:R', 'reference': 'R', 'value': '10K', 'manf#': 'ERJ-3EKF1002V'},
'R2': {u'libpart': 'device:R', 'reference': 'R', 'digikey price x1000': '0.00379', 'value': '10K', 'manf#': 'ERJ-3EKF1002V', 'digikey price x1': '0.1', u'footprint': 'Resistors_SMD:R_0603_HandSoldering', 'manufacturer pn': 'ERJ-3EKF1002V', 'digikey pn': 'P10.0KHCT-ND'},
'R3': {u'libpart': 'device:R', 'reference': 'R', 'digikey price x1000': '0.00379', 'value': '10K', 'manf#': 'ERJ-3EKF1002V', 'digikey price x1': '0.1', u'footprint': 'Resistors_SMD:R_0603_HandSoldering', 'manufacturer pn': 'ERJ-3EKF1002V', 'digikey pn': 'P10.0KHCT-ND'}}
```

You can see R2 and R3 have still got my initial fields.

I understand two similar components with different fields might have a different meaning. But I am wondering if a set of component which have the same `manf#` should always be merged together (and maybe print a warning if the hash do not correspond).

And/Or the hash could be limited to some known fields such as 'footprint', 'libpart', 'reference', 'value'.

**Comment by hildogjr** [comment]
Related with #97.
