### ISSUE TITLE
Ignoring "desc" to group components -> value absent from report

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#49]
As the description field is used as a condition to group components, I added it to the ignore list:
`kicost -d 10 -i input.xml -o ${TMPFILE} -var default --overwrite -np 5 --ignore_fields desc h`

The description field is then also absent from the excel report.

The 'desc' field should be considered the same way as the "manf#" field, or ignored fields should be stored, but only be ignored for the hashing.

**Comment by hildogjr** [comment]
Related with #97 

Maybe in the case of different `desc`, they just have to be joined in the cell as "description 1; description 2; ...". Just for spreadsheet user control.

**Comment by hildogjr** [comment]
Close and grouped with #97 for implementation.
