### ISSUE TITLE
KiCost GUI mode not working - Win7x64

### ISSUE THREAD

**Issue by sujitth** [hildogjr/KiCost#493]
- Use a simple and clear title.
- Do not mark as "ISSUE", "FEATURE" on title, this will be tagged by the development group.

#### Issue / Problem report
1. Add the KiCost version. Type ``kicost --version`` at terminal.
    KiCost 1.1.5
2. Add a terminal error report / txt, use ``--debug`` option on KiCost call;
    kicost -w -i %YOUR_FILE% --debug 8
3. Write the command used to call KiCost (or the graphical interface configuration);
    kicost
4. One BoM to reproduce the error (with the EDA version).

#### Feature / Enhancement request
- Explain how it will help the other users.
Hi @set-soft ,

The KiCost GUI mode not able to start, please refer the attached error report.
[gui_error.txt](https://github.com/xesscorp/KiCost/files/6526352/gui_error.txt)

The team thanks your contribution.

**Comment by set-soft** [comment]
Hi @sujitth!

Thanks for adding this report. Could you add the output from `kicost --info`.

I suspect this could be related to a wxWidgets problem found in version 4.1: https://github.com/DeepLabCut/DeepLabCut/issues/682

**Comment by sujitth** [comment]
Hi @set-soft ,

Please find the info:

![image](https://user-images.githubusercontent.com/6084883/119233458-c872be80-bb46-11eb-8dce-b310b1e430cc.png)

**Comment by set-soft** [comment]
Ok, can you try to downgrade wx to 4.0.7 as suggested in the issue I mentioned?

I think something like this should work:

```
pip3 install -U --upgrade wxPython==4.0.7
```

The thread says:

```
pip install -U wxPython==4.0.7.post2
```

**Comment by sujitth** [comment]
Hi @set-soft ,

wx 4.0.7 is installed.
![image](https://user-images.githubusercontent.com/6084883/119235106-759d0500-bb4e-11eb-9b29-2f65b033796c.png)

![image](https://user-images.githubusercontent.com/6084883/119235195-e8a67b80-bb4e-11eb-8f80-687f0edcedf6.png)

still gui couldn't start, please find the error report.
[gui_error2.txt](https://github.com/xesscorp/KiCost/files/6526851/gui_error2.txt)

**Comment by set-soft** [comment]
This is similar to what I have on Linux:

```
KiCost v.1.1.5 at Python 3.9.2 on Linux-5.10.0-6-amd64-x86_64-with-glibc2.31(64bit). Graphical library: 4.0.7 gtk3 (phoenix) wxWidgets 3.0.5.
```

So I don't think this is a problem of KiCost setting some locale. But just in case: Can you try commenting the `import locale` and replacing `loc = locale.getdefaultlocale()[0]` by `loc = None`?

**Comment by sujitth** [comment]
Hi @set-soft ,

Please find attached the error report after made the changes as stated above.
[Gui_error.txt](https://github.com/xesscorp/KiCost/files/6532137/Gui_error.txt)

**Comment by set-soft** [comment]
Hi @sujitth !

I added wxWidgets locale initialization. This also logs what you got initialized for wxWidgets and what Python thinks is the system locale. In my case:

```
$ kicost --debug 1 --gui tests/test2.xml
DEBUG:wxWidgets locale Spanish (Argentina) (es_AR) system: ('es_AR', 'UTF-8') (kicost - kicost_gui.py:1171)
DEBUG:Loaded KiCost v.1.1.5 (kicost - kicost_gui.py:633)
```

Please try it and tell me what you get.

**Comment by sujitth** [comment]
Hi @set-soft ,

Please find attached the error report after installing latest kicost.
Gui_test3.txt- is after making the change loc = None.

[Gui_test2.txt](https://github.com/xesscorp/KiCost/files/6536930/Gui_test2.txt)
[Gui_test3.txt](https://github.com/xesscorp/KiCost/files/6536933/Gui_test3.txt)

**Comment by set-soft** [comment]
Hi @sujitth !

> Hi @set-soft ,
> 
> Please find attached the error report after installing latest kicost.

 I need the output you get using: `kicost --debug 1 --gui tests/test2.xml` like I shown above. Do not apply the `loc = None` change, we need access to the `locale` module, and we already know that requesting `locale` isn't the problem.

IMHO this is a wxPython bug, but we should find a workaround.

**Comment by sujitth** [comment]
Hi @set-soft ,

Yes, the file Gui_test2.txt was the test output before making the loc code changes using the command provided.

I have reverted the changes made and done the test again, same output.
[Gui_test4.txt](https://github.com/xesscorp/KiCost/files/6541438/Gui_test4.txt)

**Comment by set-soft** [comment]
Hi @sujitth !

This is not the last git code. What do you get from `kicost --info`?
The last code shows information about the locale. Try reinstalling with `pip3 install -U git+https://github.com/xesscorp/KiCost.git`
`kicost --info` should inform the git hash you installed.

**Comment by sujitth** [comment]
Hi @set-soft ,

Please find the kicost --info attached below:

![image](https://user-images.githubusercontent.com/6084883/119596682-42cc6880-bdfd-11eb-914c-1cb511ad8f07.png)

**Comment by set-soft** [comment]
Hi @sujitth!

And this version doesn't print any debug information about the locale?
I mean: `kicost --debug 1 --gui tests/test2.xml` doesn't print something like this:

```
DEBUG:wxWidgets locale Spanish (Argentina) (es_AR) system: ('es_AR', 'UTF-8') (kicost - kicost_gui.py:1171)
```

**Comment by sujitth** [comment]
Hi @set-soft ,

No.

**Comment by set-soft** [comment]
Please check that line 1171 of `kicost_gui.py` is:

```
logger.debug('wxWidgets locale {} ({}) system: {}'.format(loc.GetLocale(), loc.GetName(), locale.getlocale()))
```

If this is the case:

1. Try redirecting `stderr` to a file
2. Try replacing the call to `logger.debug` by a simple `print`

**Comment by set-soft** [comment]
This log shows the source of the problem. wxWidgets is failing to set your locale.
Python is getting it right: english for India. But the value looks from Win32 API.
wxWidgets should be reporting something like: locale English (India) (en_IN)

About the changes you made for #492: What's the current value for the environment variable `LC_ALL`? Is this `en_IN`?

About point 2: never mind, it was a debug suggestion assuming you didn't get the message that you are getting.

Things will be solved when we get wxWidgets locale in sync with your system.

**Comment by sujitth** [comment]
Hi @set-soft ,

LC_ALL env var:
![image](https://user-images.githubusercontent.com/6084883/119679748-3a584a00-be5e-11eb-940b-29bbf98288ff.png)

and currently in Python:
![image](https://user-images.githubusercontent.com/6084883/119679869-55c35500-be5e-11eb-9ba2-a9d29d8dd579.png)

The GUI mode was working on KiCost - 1.0.4, the issue started after updating to current version.

**Comment by set-soft** [comment]
Your LC_ALL is wrong, doesn't match your system. Please try to define it as `en_IN`.
Python is working well because is asking to Windows. According to one of the links you sent wxWidgets is most probably asking wrongly. The proposed solution is to replace the whole locale mechanism ... an overkill.

About KiCost 1.0.4: Which wxPython and wich Python did you use with it? 

Again: I think this is purely a wxWidgets problem, nothing related to KiCost. The fact that `wx.Locale(wx.LANGUAGE_DEFAULT)` doesn't fail, but then `loc.GetLocale()` and `loc.GetName()` returns empty strings is a probe of this.

BTW: Your setup doesn't seem to be supported by wxWidgets: https://wxpython.org/Phoenix/docs/html/wx.Language.enumeration.html#wx-language  (no wx.LANGUAGE_ENGLISH_INDIA)

Things to try:
1. Properly define LC_ALL
2. Try replacing `wx.LANGUAGE_DEFAULT` by `wx.LANGUAGE_ENGLISH_US`

**Comment by sujitth** [comment]
Hi @set-soft ,
Manually set LC_ALL to `en_IN` but no effect.

> Which wxPython and wich Python did you use with it?

Python 3.6 or 3.7(anaconda), wxPython- I did't checked that time.

> 2. Try replacing wx.LANGUAGE_DEFAULT by wx.LANGUAGE_ENGLISH_US

This worked, gui mode is working now.
![image](https://user-images.githubusercontent.com/6084883/119714057-0726b280-be80-11eb-903a-48d0b216e3e1.png)

no .xlsx file is generated for test2.xml file
![image](https://user-images.githubusercontent.com/6084883/119715419-9d0f0d00-be81-11eb-9a29-eb9e889d03de.png)


and what is this thing "locale setting" is related to kicost functionality? currency setting related?

**Comment by set-soft** [comment]
Hi @sujitth !

> Manually set LC_ALL to `en_IN` but no effect.

:-(
POSIX code uses it.

> > Which wxPython and wich Python did you use with it?
> 
> Python 3.6 or 3.7(anaconda), wxPython- I did't checked that time.
> 
> > 1. Try replacing wx.LANGUAGE_DEFAULT by wx.LANGUAGE_ENGLISH_US
> 
> This worked, gui mode is working now.

Nice!
 
> and what is this thing "locale setting" is related to kicost functionality? currency setting related?

Currently: nothing at all. kiCost is currently pure "en_US". 
Your problem is most probably related to the fact that wxWidgets doesn't understand your locale, that's all. KiCost doesn't set the locale, and doesn't really need it. The getdefaultlocale() value is just for future support, this currently discarded.

Please try with the last patch.

About the fail to generate test2.xlsx: The screen capture is incomplete, the scroll bar says more text is there.

**Comment by sujitth** [comment]
Hi @set-soft ,

> The screen capture is incomplete, the scroll bar says more text is there.

No it seems, in windows the scroll bar in command prompt and content has no connection in general.
and I have attached the GUI screenshot later in the last command.

Updated to the latest git version and GUI could't start:
![image](https://user-images.githubusercontent.com/6084883/119857993-ab1c6680-bf31-11eb-8719-525bbb85a597.png)

Test- kicost --debug 1 --gui tests/test2.xml
![image](https://user-images.githubusercontent.com/6084883/119858284-f59de300-bf31-11eb-8f01-3fd8977dc35f.png)

**Comment by set-soft** [comment]
Hi @sujitth !

> > The screen capture is incomplete, the scroll bar says more text is there.
> 
> No it seems, in windows the scroll bar in command prompt and content has no connection in general.
> and I have attached the GUI screenshot later in the last command.

Then: are you sure you didn't wait enough? If KitSpace is saturated it will just time-out, see #417 
The time-out is long.

> Updated to the latest git version and GUI could't start:

Then wxWidgets is even more broken than what I thought ;-) (You can't change the locale twice using the API!)
I can't force "en_US" because this locale doesn't have to be installed on Linux boxes (I don't have it in fact). 
I added a command line option `--force_en_us` please tell me if using it solves the problem.

**Comment by sujitth** [comment]
Hi @set-soft ,

> If KitSpace is saturated it will just time-out, see #417 ,The time-out is long.

The kitspace API limit was reached and @kasbah has reset it.
This debug info is from my another test file:
![image](https://user-images.githubusercontent.com/6084883/119874542-57b31400-bf43-11eb-8e90-1431379596a1.png)

> I added a command line option --force_en_us please tell me if using it solves the problem.

This works now:
![image](https://user-images.githubusercontent.com/6084883/119874677-803b0e00-bf43-11eb-870f-d502dd4c3ffd.png)


![image](https://user-images.githubusercontent.com/6084883/119874730-8cbf6680-bf43-11eb-9a26-43a78c0c2a5d.png)

I have selected only 2 distributors only, what is the Local generated on the XL sheet?
![image](https://user-images.githubusercontent.com/6084883/119874858-b11b4300-bf43-11eb-858a-8d0ef59fcf4c.png)

**Comment by set-soft** [comment]
Hi @sujitth !

> > If KitSpace is saturated it will just time-out, see #417 ,The time-out is long.
> 
> The kitspace API limit was reached and @kasbah has reset it.
> This debug info is from my another test file:

Sorry, I don't follow you. This looks like KitSpace failing. Do you mean that you have a BoM that can generate it even when other BoMs are working? If this is the case please send me it by mail so I can try to find where is the problem.


> > I added a command line option --force_en_us please tell me if using it solves the problem.
> 
> This works now:

Ok. So now we have a workaround for systems where wxWidgets locale misserably fails. Thanks for testing it.

> I have selected only 2 distributors only, what is the Local generated on the XL sheet?

This is the mechanism that allows defining your own prices. The SW1 component defines:

```xml
        <field name="manf#">RS-282G05A3-SM RT</field>
        <field name="kicost:pricing">1:0.10;10:0.03</field>
        <field name="kicost:link">http://www.xess.com</link>
```

So you get a Unit$ of $0,03 buying 10 parts. And the URL for the part is http://www.xess.com

**Comment by sujitth** [comment]
Hi @set-soft ,

Thank you very much for resolving the issue.
