### ISSUE TITLE
Part data entry via spreadsheet

### ISSUE THREAD

**Issue by xesscorp** [hildogjr/KiCost#5]
Allow entry of BOM type data (manufacturer/manufacturer part number) into a spreadsheet (CSV) and allow import of this into the kicad project files so I can fill in manf and manf# using a spreadsheet rather than Kicad.

**Comment by Arunmaran** [comment]
Hi xesscorp,
How to import the spreadsheet in kicad for manf# field.

**Comment by xesscorp** [comment]
The separate [KiField](https://kifield.readthedocs.org/en/latest/readme.html) tool now provides the ability to enter field data into a spreadsheet and insert it into a schematic or library.

**Comment by Arunmaran** [comment]
Hi xesscorp
I got it. Thank u .

Apart from kicost and kifield any other features are there for kicad.

**Comment by xesscorp** [comment]
Currently, the only other utility is [KiPart](https://kipart.readthedocs.org/en/latest/) which helps make schematic libraries from spreadsheets containing their part pin information.
