### ISSUE TITLE
Add available stock quantity field for custom part data

### ISSUE THREAD

**Issue by hkleen** [hildogjr/KiCost#515]
I think it might be useful to allow specifying an available stock quantity for custom parts.
Analog to the pricing and link field there could be a `kicost:avail` or `kicost:My_Weird_Parts:avail` field that is used to populate the respective column in the cost spreadsheet.

This would allow to easily check if the available local stock of a custom part is sufficient to produce a given amount of boards.

**Comment by set-soft** [comment]
Hi @hkleen !
Now it can be done.
