### ISSUE TITLE
TME Cat# URLS in file:\\ format

### ISSUE THREAD

**Issue by craigarno** [hildogjr/KiCost#527]
#### Issue / Problem report
TME Hyperlinks are in the format:
\\\\www.tme.eu\en\details\2n7002-7-f\smd-n-channel-transistors\diodes-incorporated\

Converting to 
https://www.tme.eu/en/details/2n7002-7-f/smd-n-channel-transistors/diodes-incorporated/

works, but sends me to the TME EU site.  I'm in the US.  (not a big deal, I get asked if I'd like to switch to the US site.)
https://www.tme.com/us/en-us/details/2n7002-7-f/smd-n-channel-transistors/diodes-incorporated/

When I see
![image](https://user-images.githubusercontent.com/4262930/181612178-6bb69a03-d7b1-4d47-86d2-0db305b1ed38.png)
I start looking at supplier site pages and data sheets for supporting information, like what part is recommended for replacing the part which is now "not recommended for new design".

These new additions to KiCost 1.1.11 are useful.

1. Add the KiCost version. 
KiCost 1.1.11 was just installed this morning after installing KiCAD 6.0.7 which removed KiCost and KiPart from my installation.

2. Write the command used to call KiCost (or the graphical interface configuration);
![image](https://user-images.githubusercontent.com/4262930/181610028-ccd7dff7-4292-4fe8-b6c3-d79dd0c3ef62.png)

5. One BoM to reproduce the error (with the EDA version).

[USB-C PWR.xlsx](https://github.com/hildogjr/KiCost/files/9213239/USB-C.PWR.xlsx)

**Comment by set-soft** [comment]
Hi @craigarno !
Sorry for the big delay.
Is now fixed.
About the european site:
- The US counterpart (api.tme.us) resolves to a valid IP, but isn't usable
- Even when we ask for US as default country the URLs are for the european domain

**Comment by craigarno** [comment]
Hi @set-soft ,

I just received this TME communication overnight.  Is this the same issue?  Or a new issue?  Or can it be ignored?:

===

Dear Customers,
 
We would like to remind you that from the date of November 1, 2022 we introduce the format of the headers sent in API requests:
 
Content-Type: application/x-www-form-urlencoded.
 
All queries that do not meet this requirement will be rejected. Please feel free to customize your queries.
 
If you have any questions, please contact us [developers@tme.eu](mailto:developers@tme.eu)
 
Greetings
TME

**Comment by set-soft** [comment]
Hi @craigarno !
We already checked we are using the suggested method. We should be ok.

**Comment by craigarno** [comment]
@set-soft , perfect!
