### ISSUE TITLE
Variants and "same" components - BOM incorrect

### ISSUE THREAD

**Issue by mdeweerd** [hildogjr/KiCost#53]
In order to build the right BOM and cost estimate for several variants, I have added fields like this (example for 100nF):

kicost.eth:manf#  -  GRM155R71A104KA01D
manf#  - GRM155R71A104KA01D
kicost.rtc:manf#  -  GRM155R71A104KA01D

Unfortunately, in some variant combinations all 100nF capacitors are added, and in some combinations, none of the 100nF capacitors are added, while in practice just a few should be added to the BOM in any combination.

**Comment by hildogjr** [comment]
Could you add the XML and the kicost terminal commands that you are using?

**Comment by mdeweerd** [comment]
This is an old ticket - I close it and I will submit an xml file the next file I observe the behavior.
