### ISSUE TITLE
KiCost times out after reaching Kitspace API

### ISSUE THREAD

**Issue by cverrill** [hildogjr/KiCost#533]
Kicost version: 1.1.10
Command used: kicost -i CDC.xml -f DNP -w --debug=8

I've updated Kicost, obtained and added Digikey API keys. When I run Kicost, it pulls the part information from Digikey but hangs at the kitspace API part of the program. Is there a way to disable kitspace and run only with the Digikey API?
Thank you!

[kicost_log_and_xmlBom.zip](https://github.com/hildogjr/KiCost/files/9628389/kicost_log_and_xmlBom.zip)

**Comment by set-soft** [comment]
Hi @cverrill !
Yes, you just need to create a configuration file and use `enable: false`  in the `KitSpace` section. Here is the documentation about it: [Configuration file](http://hildogjr.github.io/KiCost/docs/_build/singlehtml/index.html#document-configuration)

You can also do it for one run using the `--disable_api KitSpace` option.
