### ISSUE TITLE
Warnings about APIs keys

### ISSUE THREAD

**Issue by Kralg** [hildogjr/KiCost#535]
Hello,
I am using the command: kicost -i boards.xml
I am unable to get it working, I am getting warnings:

WARNING:(WC017) Can't enable Digi-Key without a `client_id`, `client_secret` and `cache_path` (kicost.distributors - log.py:107)
WARNING:(WC017) Can't enable Mouser without a `key` (kicost.distributors - log.py:107)
WARNING:(WC017) Can't enable Elemen14 without a `key` (kicost.distributors - log.py:107)
WARNING:(WC017) Can't enable TME without a `token` and an `app_secret` (kicost.distributors - log.py:107)

Or if I run it over GUI:
Starting cost processing ...
- KitSpace [api] (https://kitspace.org/)
ERROR:One of the internal Kitspace services may experiencing problems. Most probably is saturated, please consider using other API. (kicost - __init__.py:1463)

Can you please explain do I have to register and get the tokens from each distributor and set it somehow or is this something else?

**Comment by mik1234mc** [comment]
Yes, exactly, you need to have account with all distributors you want to
see in the Kicost result Excel sheet.

The distributors provide the tokens.

**Comment by Kralg** [comment]
Thank you for the fast respone. Yeah it would be really handy to get some information in the warning in what way we can pass the tokens and what names to use. 
I believe this is system environment variables for windows?
For Mouser:
MOUSER_PART_API_KEY

For TME:
TME_TOKEN - place here "Anonymous key" from TME API. ?
TME_APP_SECRET - place here "Application secret:" -> "Token" ? 
However if I do so I am getting:

- TME [api] (https://developers.tme.eu/en/)
ERROR:Server error `Bad Request` (400) (kicost - __init__.py:1463)

Note: If I had "-" in "manf#" then I was getting this error (if that will be valuable for somebody):
ERROR:Internal error: local variable 'prj_prefix' referenced before assignment (kicost - __init__.py:1463)

**Comment by set-soft** [comment]
Hi @Kralg !
Please read the docs: [Configuration file](http://hildogjr.github.io/KiCost/docs/_build/singlehtml/index.html#document-configuration)
You don't need environment variables, you can store all in a configuration file. Note that the comments in the template config will help you to understand what is each field.
If you have example files that produce errors when using the current git code please create an issue posting the example file.
