### ISSUE TITLE
KeyError: 'Availability' on Mouser for parts with unusual status

### ISSUE THREAD

**Issue by prasetekus** [hildogjr/KiCost#542]
For parts with unusual status such as Not Available or Non-Stocked, Call for Quote on Mouser (at this moment for example parts with manf# XCF32PVOG48C and 36502A10NJTDG) KiCost stops executing with KeyError: 'Availability'. This also disables searching for the parts by the other distributors (where it can be in stock) when running in the same run. Moreover, this is a blocking error, so that no result is generated.

KiCost version v1.1.7

**Comment by set-soft** [comment]
Hi @prasetekus !
Current KiCost is 1.1.14, please try using it, if the problem is there open a new issue. I tried with XCF32PVOG48C and it didn't create a problem (even when the response doesn't contain `Availability`)
