### ISSUE TITLE
No Config File Found

### ISSUE THREAD

**Issue by david-blow** [hildogjr/KiCost#549]
Freshly installed kicost and get this.

DEBUG:No config file found (C:\Users\Camo\.config\kicost\config.yaml) (kicost - log.py:115)
DEBUG:Final API options {'Local': {}, 'Digi-Key': {}, 'Mouser': {}, 'Element14': {}, 'TME': {}, 'Nexar': {}, 'KitSpace': {}} (kicost - log.py:115)
DEBUG:API options with defaults (kicost - log.py:115)
DEBUG:- Local: (kicost - log.py:115)
DEBUG:  - cache_ttl: 7 (kicost - log.py:115)
DEBUG:  - cache_path: C:\Users\Camo/.cache/kicost\Local (kicost - log.py:115)
DEBUG:- Digi-Key: (kicost - log.py:115)
DEBUG:  - cache_ttl: 7 (kicost - log.py:115)
DEBUG:  - cache_path: C:\Users\Camo/.cache/kicost\Digi-Key (kicost - log.py:115)
DEBUG:- Mouser: (kicost - log.py:115)
DEBUG:  - cache_ttl: 7 (kicost - log.py:115)
DEBUG:  - cache_path: C:\Users\Camo/.cache/kicost\Mouser (kicost - log.py:115)
DEBUG:- Element14: (kicost - log.py:115)
DEBUG:  - cache_ttl: 7 (kicost - log.py:115)
DEBUG:  - cache_path: C:\Users\Camo/.cache/kicost\Element14 (kicost - log.py:115)
DEBUG:- TME: (kicost - log.py:115)
DEBUG:  - cache_ttl: 7 (kicost - log.py:115)
DEBUG:  - cache_path: C:\Users\Camo/.cache/kicost\TME (kicost - log.py:115)
DEBUG:- Nexar: (kicost - log.py:115)
DEBUG:  - cache_ttl: 7 (kicost - log.py:115)
DEBUG:  - cache_path: C:\Users\Camo/.cache/kicost\Nexar (kicost - log.py:115)
DEBUG:- KitSpace: (kicost - log.py:115)
DEBUG:  - cache_ttl: 7 (kicost - log.py:115)
DEBUG:  - cache_path: C:\Users\Camo/.cache/kicost\KitSpace (kicost - log.py:115)
DEBUG:Local API configured to enabled True (kicost.distributors - log.py:115)
WARNING:(WC017) Can't enable Digi-Key without a `client_id`, `client_secret` and `cache_path` (kicost.distributors - log.py:107)
DEBUG:Digi-Key API configured to enabled False id None secret None path C:\Users\Camo/.cache/kicost\Digi-Key (kicost.distributors - log.py:115)
WARNING:(WC017) Can't enable Mouser without a `key` (kicost.distributors - log.py:107)
DEBUG:Mouser API configured to enabled False key None path C:\Users\Camo/.cache/kicost\Mouser (kicost.distributors - log.py:115)
WARNING:(WC017) Can't enable Elemen14 without a `key` (kicost.distributors - log.py:107)
DEBUG:Element14 API configured to enabled False key None path C:\Users\Camo/.cache/kicost\Element14 (kicost.distributors - log.py:115)
WARNING:(WC017) Can't enable TME without a `token` and an `app_secret` (kicost.distributors - log.py:107)
DEBUG:TME API configured to enabled False token None app_secret None path C:\Users\Camo/.cache/kicost\TME (kicost.distributors - log.py:115)
WARNING:(WC017) Can't enable Nexar without a `client_id`, `client_secret` and `cache_path` (kicost.distributors - log.py:107)
DEBUG:Nexar API configured to enabled False id None secret None path C:\Users\Camo/.cache/kicost\Nexar (kicost.distributors - log.py:115)
DEBUG:KitSpace API configured to enabled False (kicost.distributors - log.py:115)
DEBUG:wxWidgets locale English (United States) (en_US) system: ('English_United States', '1252') (kicost - __init__.py:1465)
DEBUG:LibreOffice not found. (kicost - log.py:115)
DEBUG:LibreOffice not found. (kicost - log.py:115)
DEBUG:Loaded KiCost v1.1.18 (kicost - log.py:115)

**Comment by set-soft** [comment]
Hi @david-blow !
We can't register to each distributor for you, this is something you must do by yourself and create a config file with *your* credentials.
