### ISSUE TITLE
0 Qty

### ISSUE THREAD

**Issue by 466** [hildogjr/KiCost#55]
Hi there, 
i've just installed kicost using easy install, worked like a charm :)

I added manf# fields to all components in Esschema, created a BOM and used kicost on it.

Afterwards i do get an xlsx created with all parts needed, their footprints, manf# and stuff, but the quantity of each item remains zero. 
Which means each and every pcb does cost 0,00$, until i change the quantity of some items.
(So Kicost did get the price of each item) 

Any ideas on what i might have done wrong?

**Comment by xesscorp** [comment]
I'll need to see your .xml file and the resulting spreadsheet to give any recommendations.

**Comment by mazgis** [comment]
Hi, I'm facing the same issue but it looks like LibreOffice issue.
Then I select qty cell and press Function button then ok it starts working correctly. 
LibreOffice Version: 5.1.4.2 Build ID: 1:5.1.4-0ubuntu1

And just found if you change "Board Qty:" values it start working correctly

**Comment by 466** [comment]
Yeha, sorry for the late reply.
Solved it here by setting an other board quantity, too.
Seems like  "BoardQty" does  not get  initialized at startup (?)

Anyways, setting another Board quantity, updates all tables and I get the correct values :)
