### ISSUE TITLE
Configuration missing

### ISSUE THREAD

**Issue by pvolkert** [hildogjr/KiCost#554]
After installing Kicost (using pip) on my system, the config.yaml is missing, even the folders ~/.config/kicost haven't been created.

KiCost v1.1.18
System: Win11 Pro 23H2
KiCad 7.0.9
Python 3.11.3
pip 23.3.1

Starting Kicost GUI via "kicost --debug 10" command gives (only relevant lines from my feeling):
> DEBUG:No config file found (C:\Users\yyyy\.config\kicost\config.yaml) (kicost - log.py:115)
> DEBUG:Final API options {'Local': {}, 'Digi-Key': {}, 'Mouser': {}, 'Element14': {}, 'TME': {}, 'Nexar': {}, 'KitSpace': {}} (kicost - log.py:115)
> WARNING:(WC017) Can't enable Digi-Key without a `client_id`, `client_secret` and `cache_path` (kicost.distributors - log.py:107)

The warning is repeated for all distributors.

How can I get an initial config file with the necessary tokens/secrets for the distributors? I think this should be created during installation  as I cannot find a default in the git?

Thank you for your help!
Pascal

**Comment by set-soft** [comment]
See #552
