### ISSUE TITLE
MPNs containing commas are split into multiple parts

### ISSUE THREAD

**Issue by sourcebox** [hildogjr/KiCost#555]
KiCost version: 1.1.18

Parts with an MPN containing a comma like *BAT54J,115* or *BC857B,215* are split into multiple parts using the comma as delimiter.
I'm not sure if this is a bug or desired behaviour for certain cases, but there should be a way to disable it as it renders the result unusable.

**Comment by set-soft** [comment]
You can use the \ to escape these characters
