### ISSUE TITLE
LCSC distributor - how to use ?

### ISSUE THREAD

**Issue by ajohn77** [hildogjr/KiCost#559]
Hi,
I understand KiCost shall somehow support LCSC distributor, right ?
At release info 1.1.3 it is said: "Added LCSC as distributor into the Kitspace API ".
And at 1.1.6: "Fix LCSC link and add BOM import links of all"

I tried to add new line with "LCSC:" to config.yaml, but obviously this is not the way to go ("Unknown API `lcsc`")

May be I miss something obvious, but I can't find any info how to setup KiCost to include LCSC in searches.
Also it seems LCSC doesn't provide any API/keys, so I am a bit clueless how this shall work.

Would you provide some info about LCSC pls. ?

Generally it would be useful to add at least short info how to set up each distributor in KiCost doc.
E.g. a link to appropriate section of dist. web and some steps what is needed to make it working.

Anyway, thank you for your work, I find this tool extremely useful !

Alex
[KiCost v1.1.18]

**Comment by set-soft** [comment]
Just use the Nexar API
