### ISSUE TITLE
Support for other currencies

### ISSUE THREAD

**Issue by romain145** [hildogjr/KiCost#56]
Would be great to have support for international websites and other currencies.
I'm based in the uk, and access Farnell through uk.farnell.com for instance.
Would it be possible to implement this? How could I help?

**Comment by romain145** [comment]
Linked to https://github.com/xesscorp/KiCost/issues/65

**Comment by hildogjr** [comment]
Linked to #65

**Comment by hildogjr** [comment]
@romain145, discussion re-opened in #95.
For a manual work around, you can change the page scraped at `digikey.py` file to `uk.farnell.com`.
