### ISSUE TITLE
DigiKey API queries sandbox server, even when "sandbox: false" is set

### ISSUE THREAD

**Issue by salfter** [hildogjr/KiCost#565]
#### Issue / Problem report
1. Add the KiCost version. 1.1.18
2. Add a terminal error report / txt: [kicost-debug.txt](https://github.com/hildogjr/KiCost/files/15239113/kicost-debug.txt)
3. Write the command used to call KiCost (or the graphical interface configuration); ```kicost --debug 9```
4. One BoM to reproduce the error (with the EDA version). [bom.csv](https://github.com/hildogjr/KiCost/files/15239100/bom.csv), generated by KiCad 8.0.2

**Comment by set-soft** [comment]
You are overwriting it from the environment:

`DEBUG:Overwriting Digi-Key.sandbox = True (kicost.distributors - log.py:115)`
