### ISSUE TITLE
KiCost compatible with KiCad 8? XML export not availabe any more.

### ISSUE THREAD

**Issue by mxa** [hildogjr/KiCost#568]
Expanding on #557 : I don't see any option in KiCad 8 to export and XML BOM any more. Even the 3 scripts in eeschema -> "Generate legacy Bill of Materials" are all .csv.
I can't get KiCost to work without errors which don't yield any results when searching for them and the documetation is not up to date or contradicting (installation files available as .deb here on github but in the [documentation](https://hildogjr.github.io/KiCost/docs/_build/singlehtml/index.html#linux) pip install is the documented installation method.

**Comment by set-soft** [comment]
> Expanding on #557 : I don't see any option in KiCad 8 to export and XML BOM any more. Even the 3 scripts in eeschema -> "Generate legacy Bill of Materials" are all .csv.

You are not paying attention to what is generated, in order to generate the CSV KiCad must generate the XML first, so you get both: CSV and XML
