### ISSUE TITLE
comma in MPN is interpreted as subpart

### ISSUE THREAD

**Issue by stefavi** [hildogjr/KiCost#572]
Kicost v1.1.19 on Ubuntu, with Mouser API 

A MPN that contains a comma, for example [BZX884-B3V0,315](https://www.mouser.it/ProductDetail/Nexperia/BZX884-B3V0315?qs=me8TqzrmIYWwWGO0%252BKZC3Q%3D%3D) is split into subparts

![image](https://github.com/user-attachments/assets/76f75b1f-299d-417b-9899-158c1f8f5729)

**Comment by set-soft** [comment]
Yes, is documented here: https://hildogjr.github.io/KiCost/docs/_build/singlehtml/index.html#parts-with-subparts

**Comment by set-soft** [comment]
Note that you should use **BZX884-B3V0\\,315**
