### ISSUE TITLE
Ignore 'Value' as a manf# entry

### ISSUE THREAD

**Issue by whatnick** [hildogjr/KiCost#66]
In my version of KiCAD custom fields are by default assigned the string 'Value' whenever the edit window is opened for that part. For other parts this stays blank and kicost aggregation works fine. Is it possible to consider the string 'Value' as equivalent to empty for aggregation purposes.

**Comment by hildogjr** [comment]
Which version of KiCad are you using?

**Comment by whatnick** [comment]
I use nightly builds. However just an option to ignore a specific non-empty
string would be good.

**Comment by hildogjr** [comment]
May you attach here the KiCad schematic (or xml file) example if this issue? To check.
