### ISSUE TITLE
Marking parts not found at any distributor

### ISSUE THREAD

**Issue by xesscorp** [hildogjr/KiCost#7]
Instead of coloring cells green when all distributors show as blank (no part found) - it would be best to color all cells red instead.   This will help identify where no part was found.

**Comment by hildogjr** [comment]
I tried one propose of this in the last pull request #81 to the main branch, it is working fine in LibreOffice Calc but, have to be tested in some different versions of Microsoft Office.

**Comment by hildogjr** [comment]
Closed!

**Comment by hildogjr** [comment]
@xesscorp, could you close this issue? I was checking the issue list and there is at least 5 already solved but opened yet. This create some confusion in each implementation we have to focus.
