### ISSUE TITLE
Add custom fields in global part info

### ISSUE THREAD

**Issue by xesscorp** [hildogjr/KiCost#8]
Allow for other fields to be listed.  "-a room,install" as an example would add a field named "ROOM" (case insensitive) and "INSTALL" to the global part info part.   Suggest order as Refs, Value, Desc, [-a custom field 1], [-a custom field 2], [-a custom field ...], Footprint, Manf, Manf#, Qty, Unit$, Ext$.  Basically, stick the custom fields (if requested) between "Desc" and "Footprint" .   My example would show the field ROOM which I'm about to add now as ROOM="New Temp Sensor" for all parts that are part of the new temp sensor I've added.   I want to show the cost of this solution to management so I'm making a room to sort on to bring together all the costs for this feature.  For now I'm going to make a "desc" field to do this - but wouldn't mind being able to pull in custom fields to KiCost.

**Comment by NF6X** [comment]
I could sure make use of this right now, too add our internal company part number field to the kicost-generated BOM spreadsheet.
